# Generated by Django 5.1.3 on 2024-12-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0002_rename_price_house_price_per_night"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="pets_allowed",
            field=models.BooleanField(default=True),
        ),
    ]
